name: tenplate
description: Flutter frontend for 10Plate

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  http: ^1.1.0
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  web_socket_channel: ^2.4.0
  go_router: ^13.0.0
  flutter_dotenv: ^5.1.0
  flutter_markdown: ^0.7.7+1
  flutter_svg: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - .env.prod
    - assets/logo.svg
